name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: release
      uses: actions/create-release@v2
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: ${{ github.ref  }}
        tag_name: ${{ github.ref }}

    - name: upload linux artifact
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./env2js
        asset_name: env2js
